### ISSUE TITLE
Commas and quotation marks aren't being escaped properly

### ISSUE THREAD

**Issue by easton873** [testdouble/clojurescript.csv#26]
If the value [["c, a" "b"]] is given to the write-csv function, the value "c, a,b" is produced, but the value should be "\"c, a\",b". Since the string produced doesn't have these vital quotation marks, CSV readers interpret this string as three values instead of the two that were originally given in the vector which are "c, a" and "b". CSV readers work according to the spec found here: https://datatracker.ietf.org/doc/html/rfc4180

This also causes a problem with nested maps. If the value [[{:a "a" :b "b"}]] is given to the write-csv function, the value "{:a \"a\", :b \"b\"}" is produce but it should produce "\"{:a \"\"a\"\", :b \"\"b\"\"}\"".  Without the surrounding quotation marks my csv reader doesn't count these maps as one value but separates them as different values. On top of that, the quotation marks inside of a quoted value should be double quotes because this is the designated escape sequence for quotation marks in CSV. So if you want your value to be "b" then the output string should be "\"\"b\"\"".

**Comment by rosston** [comment]
You are correct that it doesn't work by default with `write-csv`. However, if you [pass `:quote? true` to `write-csv`](https://github.com/testdouble/clojurescript.csv/blob/a9bc028b302c13a2cae8c92ae2cb2c4b7f1e149e/test/testdouble/cljs/csv_test.cljs#L22-L23) as well, you'll see output of `"c, a","b"`, which is correct, although more quoted than it actually needs to be.

The package has been mostly RFC4180-compliant on `read-csv` since ~May 2019. I avoided making `write-csv` do quoting automatically because it would be a breaking change. That said, I fully acknowledge it would be nicer for `write-csv` to simply do the right thing without extra parameters.

**Comment by rosston** [comment]
Thanks to @tugh, this is now fixed in v0.6.0. 🎉
